metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 10.77.5.110, mac: '0a:a5:01:0f:f8:96', disk: sda, network_interface: eno1}
        metal1: {ansible_host: 10.77.5.111, mac: '9a:b5:62:2c:84:01', disk: sda, network_interface: eno1}
        metal2: {ansible_host: 10.77.5.112, mac: '6e:e8:5c:ca:d4:de', disk: sda, network_interface: eno1}
    workers:
      hosts:
        metal3: {ansible_host: 10.77.5.113, mac: '6a:d5:3b:06:41:f3', disk: sda, network_interface: eno1}
